name          'puppet-consul_template'
version       '0.1.0'
source        'https://github.com/gdhbashton/puppet-consul_template'
author        'gdhbashton'
license       'Apache 2.0'
summary       'Install and manage Consul Template and its jobs'
description   ''
project_page  'https://github.com/gdhbashton/puppet-consul_template'

dependency 'puppetlabs/stdlib'
